name: 'typescript test'
description: 'typescript test'
author: 'hiroshi tokudomi'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo-token:
    description: 'GITHUB TOKEN'
    required: true

  body:
    description: 'body'
    required: true

outputs:
  comment-url:
    description: 'The URL of the created comment'

runs:
  using: 'node20'
  main: 'dist/index.js'
